// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct HostLanguageDetection: Hashable, CustomStringConvertible {
  var languageCode: String? = nil
  var confidence: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HostLanguageDetection? {
    let languageCode: String? = nilOrValue(pigeonVar_list[0])
    let confidence: Double? = nilOrValue(pigeonVar_list[1])

    return HostLanguageDetection(
      languageCode: languageCode,
      confidence: confidence
    )
  }
  func toList() -> [Any?] {
    return [
      languageCode,
      confidence,
    ]
  }
  static func == (lhs: HostLanguageDetection, rhs: HostLanguageDetection) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.languageCode, rhs.languageCode) && MessagesPigeonInternal.deepEquals(lhs.confidence, rhs.confidence)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HostLanguageDetection")
    MessagesPigeonInternal.deepHash(value: languageCode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: confidence, hasher: &hasher)
  }

  public var description: String {
    return "HostLanguageDetection(languageCode: \(String(describing: languageCode)), confidence: \(String(describing: confidence)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct HostTranslationResult: Hashable, CustomStringConvertible {
  var sourceText: String? = nil
  var translatedText: String? = nil
  var sourceLanguage: String? = nil
  var targetLanguage: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HostTranslationResult? {
    let sourceText: String? = nilOrValue(pigeonVar_list[0])
    let translatedText: String? = nilOrValue(pigeonVar_list[1])
    let sourceLanguage: String? = nilOrValue(pigeonVar_list[2])
    let targetLanguage: String? = nilOrValue(pigeonVar_list[3])

    return HostTranslationResult(
      sourceText: sourceText,
      translatedText: translatedText,
      sourceLanguage: sourceLanguage,
      targetLanguage: targetLanguage
    )
  }
  func toList() -> [Any?] {
    return [
      sourceText,
      translatedText,
      sourceLanguage,
      targetLanguage,
    ]
  }
  static func == (lhs: HostTranslationResult, rhs: HostTranslationResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.sourceText, rhs.sourceText) && MessagesPigeonInternal.deepEquals(lhs.translatedText, rhs.translatedText) && MessagesPigeonInternal.deepEquals(lhs.sourceLanguage, rhs.sourceLanguage) && MessagesPigeonInternal.deepEquals(lhs.targetLanguage, rhs.targetLanguage)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HostTranslationResult")
    MessagesPigeonInternal.deepHash(value: sourceText, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: translatedText, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sourceLanguage, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: targetLanguage, hasher: &hasher)
  }

  public var description: String {
    return "HostTranslationResult(sourceText: \(String(describing: sourceText)), translatedText: \(String(describing: translatedText)), sourceLanguage: \(String(describing: sourceLanguage)), targetLanguage: \(String(describing: targetLanguage)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct HostTranslateRequest: Hashable, CustomStringConvertible {
  var text: String? = nil
  var sourceLanguage: String? = nil
  var targetLanguage: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HostTranslateRequest? {
    let text: String? = nilOrValue(pigeonVar_list[0])
    let sourceLanguage: String? = nilOrValue(pigeonVar_list[1])
    let targetLanguage: String? = nilOrValue(pigeonVar_list[2])

    return HostTranslateRequest(
      text: text,
      sourceLanguage: sourceLanguage,
      targetLanguage: targetLanguage
    )
  }
  func toList() -> [Any?] {
    return [
      text,
      sourceLanguage,
      targetLanguage,
    ]
  }
  static func == (lhs: HostTranslateRequest, rhs: HostTranslateRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.text, rhs.text) && MessagesPigeonInternal.deepEquals(lhs.sourceLanguage, rhs.sourceLanguage) && MessagesPigeonInternal.deepEquals(lhs.targetLanguage, rhs.targetLanguage)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HostTranslateRequest")
    MessagesPigeonInternal.deepHash(value: text, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sourceLanguage, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: targetLanguage, hasher: &hasher)
  }

  public var description: String {
    return "HostTranslateRequest(text: \(String(describing: text)), sourceLanguage: \(String(describing: sourceLanguage)), targetLanguage: \(String(describing: targetLanguage)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct HostTranslateBatchRequest: Hashable, CustomStringConvertible {
  var texts: [String]? = nil
  var sourceLanguage: String? = nil
  var targetLanguage: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HostTranslateBatchRequest? {
    let texts: [String]? = nilOrValue(pigeonVar_list[0])
    let sourceLanguage: String? = nilOrValue(pigeonVar_list[1])
    let targetLanguage: String? = nilOrValue(pigeonVar_list[2])

    return HostTranslateBatchRequest(
      texts: texts,
      sourceLanguage: sourceLanguage,
      targetLanguage: targetLanguage
    )
  }
  func toList() -> [Any?] {
    return [
      texts,
      sourceLanguage,
      targetLanguage,
    ]
  }
  static func == (lhs: HostTranslateBatchRequest, rhs: HostTranslateBatchRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.texts, rhs.texts) && MessagesPigeonInternal.deepEquals(lhs.sourceLanguage, rhs.sourceLanguage) && MessagesPigeonInternal.deepEquals(lhs.targetLanguage, rhs.targetLanguage)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HostTranslateBatchRequest")
    MessagesPigeonInternal.deepHash(value: texts, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sourceLanguage, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: targetLanguage, hasher: &hasher)
  }

  public var description: String {
    return "HostTranslateBatchRequest(texts: \(String(describing: texts)), sourceLanguage: \(String(describing: sourceLanguage)), targetLanguage: \(String(describing: targetLanguage)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return HostLanguageDetection.fromList(self.readValue() as! [Any?])
    case 130:
      return HostTranslationResult.fromList(self.readValue() as! [Any?])
    case 131:
      return HostTranslateRequest.fromList(self.readValue() as! [Any?])
    case 132:
      return HostTranslateBatchRequest.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? HostLanguageDetection {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? HostTranslationResult {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? HostTranslateRequest {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? HostTranslateBatchRequest {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol LocalTranslationHostApi {
  func isSupported() throws -> Bool
  func detectLanguage(text: String, completion: @escaping (Result<HostLanguageDetection, Error>) -> Void)
  func detectLanguages(texts: [String], completion: @escaping (Result<[HostLanguageDetection], Error>) -> Void)
  func translate(request: HostTranslateRequest, completion: @escaping (Result<HostTranslationResult, Error>) -> Void)
  func translateBatch(request: HostTranslateBatchRequest, completion: @escaping (Result<[HostTranslationResult], Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class LocalTranslationHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `LocalTranslationHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: LocalTranslationHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let isSupportedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.local_translation.LocalTranslationHostApi.isSupported\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isSupportedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isSupported()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isSupportedChannel.setMessageHandler(nil)
    }
    let detectLanguageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.local_translation.LocalTranslationHostApi.detectLanguage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      detectLanguageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let textArg = args[0] as! String
        api.detectLanguage(text: textArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      detectLanguageChannel.setMessageHandler(nil)
    }
    let detectLanguagesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.local_translation.LocalTranslationHostApi.detectLanguages\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      detectLanguagesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let textsArg = args[0] as! [String]
        api.detectLanguages(texts: textsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      detectLanguagesChannel.setMessageHandler(nil)
    }
    let translateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.local_translation.LocalTranslationHostApi.translate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      translateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! HostTranslateRequest
        api.translate(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      translateChannel.setMessageHandler(nil)
    }
    let translateBatchChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.local_translation.LocalTranslationHostApi.translateBatch\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      translateBatchChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! HostTranslateBatchRequest
        api.translateBatch(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      translateBatchChannel.setMessageHandler(nil)
    }
  }
}
