// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.ae1.local_translation

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class HostLanguageDetection (
  val languageCode: String? = null,
  val confidence: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): HostLanguageDetection {
      val languageCode = pigeonVar_list[0] as String?
      val confidence = pigeonVar_list[1] as Double?
      return HostLanguageDetection(languageCode, confidence)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      languageCode,
      confidence,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as HostLanguageDetection
    return MessagesPigeonUtils.deepEquals(this.languageCode, other.languageCode) && MessagesPigeonUtils.deepEquals(this.confidence, other.confidence)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.languageCode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.confidence)
    return result
  }
  override fun toString(): String {
    return "HostLanguageDetection(languageCode=$languageCode, confidence=$confidence)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class HostTranslationResult (
  val sourceText: String? = null,
  val translatedText: String? = null,
  val sourceLanguage: String? = null,
  val targetLanguage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): HostTranslationResult {
      val sourceText = pigeonVar_list[0] as String?
      val translatedText = pigeonVar_list[1] as String?
      val sourceLanguage = pigeonVar_list[2] as String?
      val targetLanguage = pigeonVar_list[3] as String?
      return HostTranslationResult(sourceText, translatedText, sourceLanguage, targetLanguage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sourceText,
      translatedText,
      sourceLanguage,
      targetLanguage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as HostTranslationResult
    return MessagesPigeonUtils.deepEquals(this.sourceText, other.sourceText) && MessagesPigeonUtils.deepEquals(this.translatedText, other.translatedText) && MessagesPigeonUtils.deepEquals(this.sourceLanguage, other.sourceLanguage) && MessagesPigeonUtils.deepEquals(this.targetLanguage, other.targetLanguage)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sourceText)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.translatedText)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sourceLanguage)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.targetLanguage)
    return result
  }
  override fun toString(): String {
    return "HostTranslationResult(sourceText=$sourceText, translatedText=$translatedText, sourceLanguage=$sourceLanguage, targetLanguage=$targetLanguage)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class HostTranslateRequest (
  val text: String? = null,
  val sourceLanguage: String? = null,
  val targetLanguage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): HostTranslateRequest {
      val text = pigeonVar_list[0] as String?
      val sourceLanguage = pigeonVar_list[1] as String?
      val targetLanguage = pigeonVar_list[2] as String?
      return HostTranslateRequest(text, sourceLanguage, targetLanguage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      text,
      sourceLanguage,
      targetLanguage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as HostTranslateRequest
    return MessagesPigeonUtils.deepEquals(this.text, other.text) && MessagesPigeonUtils.deepEquals(this.sourceLanguage, other.sourceLanguage) && MessagesPigeonUtils.deepEquals(this.targetLanguage, other.targetLanguage)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.text)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sourceLanguage)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.targetLanguage)
    return result
  }
  override fun toString(): String {
    return "HostTranslateRequest(text=$text, sourceLanguage=$sourceLanguage, targetLanguage=$targetLanguage)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class HostTranslateBatchRequest (
  val texts: List<String>? = null,
  val sourceLanguage: String? = null,
  val targetLanguage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): HostTranslateBatchRequest {
      val texts = pigeonVar_list[0] as List<String>?
      val sourceLanguage = pigeonVar_list[1] as String?
      val targetLanguage = pigeonVar_list[2] as String?
      return HostTranslateBatchRequest(texts, sourceLanguage, targetLanguage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      texts,
      sourceLanguage,
      targetLanguage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as HostTranslateBatchRequest
    return MessagesPigeonUtils.deepEquals(this.texts, other.texts) && MessagesPigeonUtils.deepEquals(this.sourceLanguage, other.sourceLanguage) && MessagesPigeonUtils.deepEquals(this.targetLanguage, other.targetLanguage)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.texts)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sourceLanguage)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.targetLanguage)
    return result
  }
  override fun toString(): String {
    return "HostTranslateBatchRequest(texts=$texts, sourceLanguage=$sourceLanguage, targetLanguage=$targetLanguage)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HostLanguageDetection.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HostTranslationResult.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HostTranslateRequest.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HostTranslateBatchRequest.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is HostLanguageDetection -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is HostTranslationResult -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is HostTranslateRequest -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is HostTranslateBatchRequest -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface LocalTranslationHostApi {
  fun isSupported(callback: (Result<Boolean>) -> Unit)
  fun detectLanguage(text: String, callback: (Result<HostLanguageDetection>) -> Unit)
  fun detectLanguages(texts: List<String>, callback: (Result<List<HostLanguageDetection>>) -> Unit)
  fun translate(request: HostTranslateRequest, callback: (Result<HostTranslationResult>) -> Unit)
  fun translateBatch(request: HostTranslateBatchRequest, callback: (Result<List<HostTranslationResult>>) -> Unit)

  companion object {
    /** The codec used by LocalTranslationHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `LocalTranslationHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: LocalTranslationHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.local_translation.LocalTranslationHostApi.isSupported$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isSupported{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.local_translation.LocalTranslationHostApi.detectLanguage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textArg = args[0] as String
            api.detectLanguage(textArg) { result: Result<HostLanguageDetection> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.local_translation.LocalTranslationHostApi.detectLanguages$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textsArg = args[0] as List<String>
            api.detectLanguages(textsArg) { result: Result<List<HostLanguageDetection>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.local_translation.LocalTranslationHostApi.translate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as HostTranslateRequest
            api.translate(requestArg) { result: Result<HostTranslationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.local_translation.LocalTranslationHostApi.translateBatch$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as HostTranslateBatchRequest
            api.translateBatch(requestArg) { result: Result<List<HostTranslationResult>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
