// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

class HostLanguageDetection {
  HostLanguageDetection({this.languageCode, this.confidence});

  String? languageCode;

  double? confidence;

  List<Object?> _toList() {
    return <Object?>[languageCode, confidence];
  }

  Object encode() {
    return _toList();
  }

  static HostLanguageDetection decode(Object result) {
    result as List<Object?>;
    return HostLanguageDetection(
      languageCode: result[0] as String?,
      confidence: result[1] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HostLanguageDetection || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(languageCode, other.languageCode) &&
        _deepEquals(confidence, other.confidence);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HostLanguageDetection(languageCode: $languageCode, confidence: $confidence)';
  }
}

class HostTranslationResult {
  HostTranslationResult({
    this.sourceText,
    this.translatedText,
    this.sourceLanguage,
    this.targetLanguage,
  });

  String? sourceText;

  String? translatedText;

  String? sourceLanguage;

  String? targetLanguage;

  List<Object?> _toList() {
    return <Object?>[
      sourceText,
      translatedText,
      sourceLanguage,
      targetLanguage,
    ];
  }

  Object encode() {
    return _toList();
  }

  static HostTranslationResult decode(Object result) {
    result as List<Object?>;
    return HostTranslationResult(
      sourceText: result[0] as String?,
      translatedText: result[1] as String?,
      sourceLanguage: result[2] as String?,
      targetLanguage: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HostTranslationResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sourceText, other.sourceText) &&
        _deepEquals(translatedText, other.translatedText) &&
        _deepEquals(sourceLanguage, other.sourceLanguage) &&
        _deepEquals(targetLanguage, other.targetLanguage);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HostTranslationResult(sourceText: $sourceText, translatedText: $translatedText, sourceLanguage: $sourceLanguage, targetLanguage: $targetLanguage)';
  }
}

class HostTranslateRequest {
  HostTranslateRequest({this.text, this.sourceLanguage, this.targetLanguage});

  String? text;

  String? sourceLanguage;

  String? targetLanguage;

  List<Object?> _toList() {
    return <Object?>[text, sourceLanguage, targetLanguage];
  }

  Object encode() {
    return _toList();
  }

  static HostTranslateRequest decode(Object result) {
    result as List<Object?>;
    return HostTranslateRequest(
      text: result[0] as String?,
      sourceLanguage: result[1] as String?,
      targetLanguage: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HostTranslateRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(text, other.text) &&
        _deepEquals(sourceLanguage, other.sourceLanguage) &&
        _deepEquals(targetLanguage, other.targetLanguage);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HostTranslateRequest(text: $text, sourceLanguage: $sourceLanguage, targetLanguage: $targetLanguage)';
  }
}

class HostTranslateBatchRequest {
  HostTranslateBatchRequest({
    this.texts,
    this.sourceLanguage,
    this.targetLanguage,
  });

  List<String>? texts;

  String? sourceLanguage;

  String? targetLanguage;

  List<Object?> _toList() {
    return <Object?>[texts, sourceLanguage, targetLanguage];
  }

  Object encode() {
    return _toList();
  }

  static HostTranslateBatchRequest decode(Object result) {
    result as List<Object?>;
    return HostTranslateBatchRequest(
      texts: (result[0] as List<Object?>?)?.cast<String>(),
      sourceLanguage: result[1] as String?,
      targetLanguage: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HostTranslateBatchRequest ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(texts, other.texts) &&
        _deepEquals(sourceLanguage, other.sourceLanguage) &&
        _deepEquals(targetLanguage, other.targetLanguage);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HostTranslateBatchRequest(texts: $texts, sourceLanguage: $sourceLanguage, targetLanguage: $targetLanguage)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is HostLanguageDetection) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is HostTranslationResult) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is HostTranslateRequest) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is HostTranslateBatchRequest) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return HostLanguageDetection.decode(readValue(buffer)!);
      case 130:
        return HostTranslationResult.decode(readValue(buffer)!);
      case 131:
        return HostTranslateRequest.decode(readValue(buffer)!);
      case 132:
        return HostTranslateBatchRequest.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class LocalTranslationHostApi {
  /// Constructor for [LocalTranslationHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  LocalTranslationHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<bool> isSupported() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.local_translation.LocalTranslationHostApi.isSupported$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<HostLanguageDetection> detectLanguage(String text) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.local_translation.LocalTranslationHostApi.detectLanguage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[text],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as HostLanguageDetection;
  }

  Future<List<HostLanguageDetection>> detectLanguages(
    List<String> texts,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.local_translation.LocalTranslationHostApi.detectLanguages$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[texts],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>)
        .cast<HostLanguageDetection>();
  }

  Future<HostTranslationResult> translate(HostTranslateRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.local_translation.LocalTranslationHostApi.translate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as HostTranslationResult;
  }

  Future<List<HostTranslationResult>> translateBatch(
    HostTranslateBatchRequest request,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.local_translation.LocalTranslationHostApi.translateBatch$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>)
        .cast<HostTranslationResult>();
  }
}
